# Generated by Django 4.2 on 2023-09-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=70)),
                ('phone', models.IntegerField()),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
    ]
